const state={index:null,plan:null,activeView:'today',activeDay:null};const els={};document.addEventListener('DOMContentLoaded',init);
async function init(){mapElements();bindEvents();try{await loadPlanIndex();populateWeekSelector();const preferred=getPlanFromUrl()||localStorage.getItem('selectedPlan')||state.index.latest;await loadPlan(preferred);registerServiceWorker()}catch(error){showError(error)}}
function mapElements(){['app-title','date-range','week-select','update-status','main-content','today-content','week-content','grocery-text','copy-status','archive-list','error-panel','error-message'].forEach(id=>els[id.replaceAll('-','')]=document.getElementById(id))}
function bindEvents(){document.querySelectorAll('.nav-button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.getElementById('refresh-button').addEventListener('click',refreshCurrentPlan);document.getElementById('copy-groceries').addEventListener('click',copyGroceries);document.getElementById('week-select').addEventListener('change',e=>loadPlan(e.target.value))}
async function loadPlanIndex(){state.index=await fetchJson('./plans/index.json',true);if(!state.index?.latest||!Array.isArray(state.index.plans))throw new Error('plans/index.json is missing required fields.')}
function populateWeekSelector(){els.weekselect.innerHTML='';[...state.index.plans].sort((a,b)=>b.startDate.localeCompare(a.startDate)).forEach(meta=>{const o=document.createElement('option');o.value=meta.id;o.textContent=meta.title;els.weekselect.appendChild(o)})}
async function loadPlan(planId,force=false){const meta=state.index.plans.find(x=>x.id===planId)||state.index.plans.find(x=>x.id===state.index.latest);if(!meta)throw new Error('No meal plans are listed.');setStatus('Loading plan…');const suffix=force?`?v=${Date.now()}`:'';const plan=await fetchJson(`./plans/${meta.file}${suffix}`,force);validatePlan(plan);state.plan=plan;state.activeDay=getBestDefaultDay(plan);els.weekselect.value=meta.id;localStorage.setItem('selectedPlan',meta.id);updateUrl(meta.id);renderAll();setStatus(force?'Updated with the latest version.':'')}
async function refreshCurrentPlan(){try{await loadPlanIndex();populateWeekSelector();await loadPlan(state.plan?.id||state.index.latest,true)}catch(e){setStatus('Refresh failed. Showing the last loaded plan.');console.error(e)}}
function renderAll(){els.apptitle.textContent=state.plan.title;els.daterange.textContent=formatDateRange(state.plan.startDate,state.plan.endDate);renderToday();renderWeek();renderGroceries();renderArchive();document.getElementById('footer-version').textContent=`Meal Plan PWA · Plan updated ${formatDate(state.plan.updatedAt||state.plan.startDate)}`}
function renderToday(){const x=getTodayForPlan(state.plan),d=x.day;els.todaycontent.innerHTML=`<article class="today-hero card"><p class="eyebrow">${x.isActualToday?'Today':'Selected week'}</p><h2>${esc(d.day)}</h2><p>${esc(formatDate(d.date))}</p></article><div class="meal-stack">${mealCard('Breakfast',d.breakfast)}${mealCard('Lunch',d.lunch)}${mealCard('Dinner',d.dinner)}</div>${d.dayNotes?.length?notes(d.dayNotes):''}`}
function renderWeek(){els.weekcontent.innerHTML=state.plan.days.map(d=>`<article class="week-day-card"><div class="week-day-header"><div><p class="eyebrow">${esc(d.day)}</p><h3>${esc(formatDate(d.date))}</h3></div></div><div class="week-day-meals">${weekMeal('Breakfast',d.breakfast)}${weekMeal('Lunch',d.lunch)}${weekMeal('Dinner',d.dinner)}</div>${d.dayNotes?.length?notes(d.dayNotes):''}</article>`).join('')}
function weekMeal(type,m){return `<section class="week-meal"><div class="week-meal-heading"><span>${esc(type)}</span><strong>${esc(m.name)}</strong></div><div class="person-grid">${person('Dusty',m.dusty)}${person('Sam',m.sam)}</div>${m.note?`<p class="meal-note">${esc(m.note)}</p>`:''}</section>`}
function mealCard(type,m){return `<article class="meal-card"><div class="meal-card-header"><div><div class="meal-type">${esc(type)}</div><h3>${esc(m.name)}</h3></div></div><div class="person-grid">${person('Dusty',m.dusty)}${person('Sam',m.sam)}</div>${m.note?`<p class="meal-note">${esc(m.note)}</p>`:''}</article>`}
function person(name,items){const vals=Array.isArray(items)?items:[items].filter(Boolean);return `<div class="person-card"><strong>${name}</strong><ul class="portion-list">${vals.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`}
function notes(items){return `<div class="meal-note">${items.map(esc).join('<br>')}</div>`}
function renderGroceries(){els.grocerytext.value=(state.plan.groceries||[]).join('\n');els.copystatus.textContent=''}
function renderArchive(){const plans=[...state.index.plans].sort((a,b)=>b.startDate.localeCompare(a.startDate));els.archivelist.innerHTML='';if(plans.length<=1){els.archivelist.innerHTML='<div class="empty-state">Older meal plans will appear here after you add them to plans/index.json.</div>';return}plans.forEach(meta=>{const b=document.createElement('button');b.className='archive-item';b.innerHTML=`<span><strong>${esc(meta.title)}</strong><span>${esc(formatDateRange(meta.startDate,meta.endDate))}</span></span><span class="archive-arrow">›</span>`;b.addEventListener('click',async()=>{await loadPlan(meta.id);setView('today');scrollTo({top:0,behavior:'smooth'})});els.archivelist.appendChild(b)})}
async function copyGroceries(){const text=els.grocerytext.value.trim();if(!text){els.copystatus.textContent='There is no grocery list in this plan.';return}try{await navigator.clipboard.writeText(text)}catch{els.grocerytext.focus();els.grocerytext.select();document.execCommand('copy')}els.copystatus.textContent='Grocery list copied.'}
function setView(name){document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));els.maincontent.focus({preventScroll:true})}
function getTodayForPlan(plan){const iso=localDateIso(new Date()),actual=plan.days.find(d=>d.date===iso);return actual?{day:actual,isActualToday:true}:{day:plan.days.find(d=>d.date===state.activeDay)||plan.days[0],isActualToday:false}}
function getBestDefaultDay(plan){const iso=localDateIso(new Date());return plan.days.some(d=>d.date===iso)?iso:plan.days[0].date}
function getPlanFromUrl(){return new URLSearchParams(location.search).get('week')}
function updateUrl(id){const u=new URL(location.href);u.searchParams.set('week',id);history.replaceState({},'',u)}
async function fetchJson(url,noStore=false){const r=await fetch(url,{cache:noStore?'no-store':'default'});if(!r.ok)throw new Error(`Unable to load ${url} (${r.status}).`);return r.json()}
function validatePlan(p){for(const k of ['id','title','startDate','endDate','days','groceries'])if(p[k]===undefined)throw new Error(`Meal-plan JSON is missing ${k}.`);if(!Array.isArray(p.days)||p.days.length!==7)throw new Error('Each meal plan must include exactly seven days.');if(!Array.isArray(p.groceries))throw new Error('Groceries must be a plain array of lines.')}
function setStatus(m){els.updatestatus.textContent=m}
function showError(e){console.error(e);els.errormessage.textContent=e.message||'Check your connection and refresh.';els.errorpanel.classList.remove('hidden')}
function localDateIso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function formatDate(v){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${v}T12:00:00`))}
function formatDateRange(s,e){const a=new Date(`${s}T12:00:00`),b=new Date(`${e}T12:00:00`),sameYear=a.getFullYear()===b.getFullYear(),sameMonth=sameYear&&a.getMonth()===b.getMonth();return sameMonth?`${new Intl.DateTimeFormat('en-US',{month:'long'}).format(a)} ${a.getDate()}–${b.getDate()}, ${b.getFullYear()}`:`${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(a)}–${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(b)}`}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function registerServiceWorker(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error)}
